// Generated by gencpp from file Exercise_two/Info2.msg
// DO NOT EDIT!


#ifndef EXERCISE_TWO_MESSAGE_INFO2_H
#define EXERCISE_TWO_MESSAGE_INFO2_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace Exercise_two
{
template <class ContainerAllocator>
struct Info2_
{
  typedef Info2_<ContainerAllocator> Type;

  Info2_()
    : name()
    , age(0)
    , height(0)  {
    }
  Info2_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , age(0)
    , height(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;

   typedef int64_t _age_type;
  _age_type age;

   typedef int64_t _height_type;
  _height_type height;





  typedef boost::shared_ptr< ::Exercise_two::Info2_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::Exercise_two::Info2_<ContainerAllocator> const> ConstPtr;

}; // struct Info2_

typedef ::Exercise_two::Info2_<std::allocator<void> > Info2;

typedef boost::shared_ptr< ::Exercise_two::Info2 > Info2Ptr;
typedef boost::shared_ptr< ::Exercise_two::Info2 const> Info2ConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::Exercise_two::Info2_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::Exercise_two::Info2_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::Exercise_two::Info2_<ContainerAllocator1> & lhs, const ::Exercise_two::Info2_<ContainerAllocator2> & rhs)
{
  return lhs.name == rhs.name &&
    lhs.age == rhs.age &&
    lhs.height == rhs.height;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::Exercise_two::Info2_<ContainerAllocator1> & lhs, const ::Exercise_two::Info2_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace Exercise_two

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::Exercise_two::Info2_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::Exercise_two::Info2_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::Exercise_two::Info2_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::Exercise_two::Info2_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::Exercise_two::Info2_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::Exercise_two::Info2_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::Exercise_two::Info2_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f0d4bd406180745d45cbb307c74814b7";
  }

  static const char* value(const ::Exercise_two::Info2_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf0d4bd406180745dULL;
  static const uint64_t static_value2 = 0x45cbb307c74814b7ULL;
};

template<class ContainerAllocator>
struct DataType< ::Exercise_two::Info2_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Exercise_two/Info2";
  }

  static const char* value(const ::Exercise_two::Info2_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::Exercise_two::Info2_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string name\n"
"int64 age\n"
"int64 height\n"
;
  }

  static const char* value(const ::Exercise_two::Info2_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::Exercise_two::Info2_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.age);
      stream.next(m.height);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Info2_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::Exercise_two::Info2_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::Exercise_two::Info2_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
    s << indent << "age: ";
    Printer<int64_t>::stream(s, indent + "  ", v.age);
    s << indent << "height: ";
    Printer<int64_t>::stream(s, indent + "  ", v.height);
  }
};

} // namespace message_operations
} // namespace ros

#endif // EXERCISE_TWO_MESSAGE_INFO2_H
