// Generated by gencpp from file Exercise_one/Info.msg
// DO NOT EDIT!


#ifndef EXERCISE_ONE_MESSAGE_INFO_H
#define EXERCISE_ONE_MESSAGE_INFO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace Exercise_one
{
template <class ContainerAllocator>
struct Info_
{
  typedef Info_<ContainerAllocator> Type;

  Info_()
    : name()
    , age(0)
    , height(0)  {
    }
  Info_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , age(0)
    , height(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;

   typedef int8_t _age_type;
  _age_type age;

   typedef int32_t _height_type;
  _height_type height;





  typedef boost::shared_ptr< ::Exercise_one::Info_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::Exercise_one::Info_<ContainerAllocator> const> ConstPtr;

}; // struct Info_

typedef ::Exercise_one::Info_<std::allocator<void> > Info;

typedef boost::shared_ptr< ::Exercise_one::Info > InfoPtr;
typedef boost::shared_ptr< ::Exercise_one::Info const> InfoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::Exercise_one::Info_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::Exercise_one::Info_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::Exercise_one::Info_<ContainerAllocator1> & lhs, const ::Exercise_one::Info_<ContainerAllocator2> & rhs)
{
  return lhs.name == rhs.name &&
    lhs.age == rhs.age &&
    lhs.height == rhs.height;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::Exercise_one::Info_<ContainerAllocator1> & lhs, const ::Exercise_one::Info_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace Exercise_one

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::Exercise_one::Info_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::Exercise_one::Info_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::Exercise_one::Info_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::Exercise_one::Info_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::Exercise_one::Info_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::Exercise_one::Info_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::Exercise_one::Info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c9ff281cbd003aff395267934689225f";
  }

  static const char* value(const ::Exercise_one::Info_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc9ff281cbd003affULL;
  static const uint64_t static_value2 = 0x395267934689225fULL;
};

template<class ContainerAllocator>
struct DataType< ::Exercise_one::Info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Exercise_one/Info";
  }

  static const char* value(const ::Exercise_one::Info_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::Exercise_one::Info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string name\n"
"int8 age\n"
"int32 height\n"
;
  }

  static const char* value(const ::Exercise_one::Info_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::Exercise_one::Info_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.age);
      stream.next(m.height);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Info_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::Exercise_one::Info_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::Exercise_one::Info_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
    s << indent << "age: ";
    Printer<int8_t>::stream(s, indent + "  ", v.age);
    s << indent << "height: ";
    Printer<int32_t>::stream(s, indent + "  ", v.height);
  }
};

} // namespace message_operations
} // namespace ros

#endif // EXERCISE_ONE_MESSAGE_INFO_H
